name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          architecture: x64
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
      - name: Installation
        run: |
          yarn
      - name: Linting
        run: |
          yarn lint

  test:
    name: Testing on Node ${{ matrix.node-version }} ${{ matrix.os }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14, 16]
        architecture: [x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
      - name: Installation
        run: |
          yarn
      - name: Testing
        run: |
          yarn test
          yarn badge
      - name: Coveralls action
        uses: coverallsapp/github-action@1.1.3
        if: ${{ matrix.node-version == 16 && matrix.os == 'ubuntu-latest' && matrix.architecture == 'x64' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: Node ${{ matrix.node-version }} ${{ matrix.os }} ${{ matrix.architecture }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        if: ${{ matrix.node-version == 16 && matrix.os == 'ubuntu-latest' && matrix.architecture == 'x64' }}
        with:
          name: badges
          path: build

  build:
    name: Building on Node ${{ matrix.node-version }} ${{ matrix.os }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14, 16]
        architecture: [x64]
    steps:
      - name: Setup git configuration
        run: |
          git config --global core.autocrlf false
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.architecture }}
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
      - name: Installation
        run: |
          yarn
      - name: Building work
        run: |
          yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        if: ${{ matrix.node-version == 16 && matrix.os == 'ubuntu-latest' && matrix.architecture == 'x64' }}
        with:
          name: demos
          path: build

  deploy:
    name: Deployment
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v2
      - name: List production artifacts
        run: |
          ls -R
        working-directory: .
      - name: Aggregate production artifacts
        run: |
          mkdir -p ./build/
          cp -fr badges/* ./build/
          cp -fr demos/* ./build/
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
